# Generated by Django 6.1.1 on 2026-09-09 21:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('perfil', models.CharField(choices=[('GERENTE', 'Gerente'), ('VENDEDOR', 'Vendedor'), ('ADMINISTRATIVO', 'Administrativo')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcada_desconto', models.DecimalField(decimal_places=2, default=0, help_text='Percentual máximo de desconto que este vendedor pode aplicar sem aprovação.', max_digits=5)),
                ('percentual_comissao', models.DecimalField(decimal_places=2, default=0, help_text='Percentual de comissão do vendedor sobre a margem da venda.', max_digits=5)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edicoes_alcada_comissao', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(limit_choices_to={'perfil': 'VENDEDOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='dados_vendedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8)),
                ('chassi', models.CharField(max_length=17)),
                ('marca', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=60)),
                ('ano_fabricacao', models.PositiveSmallIntegerField()),
                ('ano_modelo', models.PositiveSmallIntegerField()),
                ('cor', models.CharField(max_length=30)),
                ('combustivel', models.CharField(max_length=30)),
                ('quilometragem', models.PositiveIntegerField()),
                ('opcionais', models.TextField(blank=True)),
                ('origem', models.CharField(choices=[('COMPRADO', 'Comprado de terceiro'), ('TROCA', 'Recebido em troca'), ('CONSIGNADO', 'Consignado')], max_length=20)),
                ('custo_aquisicao', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_repasse', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('venda_fechada', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('RESERVADO', 'Reservado'), ('VENDIDO', 'Vendido')], default='DISPONIVEL', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos_cadastrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservaVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=120)),
                ('cliente_contato', models.CharField(max_length=60)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('cancelada', models.BooleanField(default=False)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_feitas', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.OneToOneField(limit_choices_to={'status': 'DISPONIVEL'}, on_delete=django.db.models.deletion.CASCADE, related_name='reserva_ativa', to='core.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CUSTO_AQUISICAO', 'Custo de aquisição'), ('DESPESA', 'Despesa (preparo, documentação, etc.)'), ('VENDA', 'Valor de venda'), ('COMISSAO', 'Comissão paga')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='core.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='FotoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='veiculos/%Y/%m/')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('principal', models.BooleanField(default=False)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.veiculo')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.AddConstraint(
            model_name='veiculo',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['DISPONIVEL', 'RESERVADO'])), fields=('placa',), name='placa_unica_estoque_ativo'),
        ),
        migrations.AddConstraint(
            model_name='veiculo',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['DISPONIVEL', 'RESERVADO'])), fields=('chassi',), name='chassi_unico_estoque_ativo'),
        ),
    ]
