# Generated by Django 5.1.4 on 2026-09-13 20:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_fotoveiculo_id_alter_lancamentofinanceiro_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoAgendado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=120)),
                ('cliente_contato', models.CharField(max_length=60)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('data_prevista', models.DateField(default=django.utils.timezone.now)),
                ('concluido', models.BooleanField(default=False)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fila_contato', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_prevista'],
            },
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=120)),
                ('valor_proposto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada'), ('AGUARDANDO_GERENTE', 'Aguardando aprovação do gerente')], default='ABERTA', max_length=25)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propostas', to='core.veiculo')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propostas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
