# Generated by Django 6.1.1 on 2026-09-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_veiculo_renavam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='renavam',
            field=models.CharField(max_length=11),
        ),
    ]
