# Generated by Django 5.1.4 on 2026-09-21 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_veiculo_renavam'),
        ('core', '0003_contatoagendado_proposta'),
    ]

    operations = [
    ]
