# Generated by Django 5.1.4 on 2026-09-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20260921_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposta',
            name='veiculo',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='situacao',
            field=models.CharField(choices=[('PREPARACAO', 'Em preparação'), ('DISPONIVEL', 'Disponível'), ('RESERVADO', 'Reservado'), ('VENDIDO', 'Vendido'), ('ENTREGUE', 'Entregue')], default='PREPARACAO', max_length=20),
        ),
        migrations.DeleteModel(
            name='ContatoAgendado',
        ),
        migrations.DeleteModel(
            name='Proposta',
        ),
    ]
