# Generated by Django 5.1.4 on 2026-09-21 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_proposta_veiculo_remove_proposta_vendedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoSituacaoVeiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('situacao_nova', models.CharField(max_length=20)),
                ('alterado_em', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('alterado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alteracoes_situacao_veiculo', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_situacoes', to='core.veiculo')),
            ],
        ),
    ]
