# Generated by Django 5.1.4 on 2026-09-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_historicosituacaoveiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='preco_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
