# Generated by Django 5.1.4 on 2026-09-22 15:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_veiculo_preco_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='data_lancamento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='editado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='editado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despesas_editadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='excluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='excluido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despesas_excluidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistoricoPrecoVeiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_novo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('custo_total_no_momento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('abaixo_do_custo', models.BooleanField(default=False)),
                ('alterado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alteracoes_preco_veiculo', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_precos', to='core.veiculo')),
            ],
        ),
    ]
