# Generated by Django 5.1.4 on 2026-09-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lancamentofinanceiro_data_lancamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilvendedor',
            name='alcada_desconto',
        ),
        migrations.AddField(
            model_name='perfilvendedor',
            name='tipo_alcada',
            field=models.CharField(choices=[('PERCENTUAL', 'Percentual (%)'), ('VALOR', 'Valor (R$)')], default='PERCENTUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='perfilvendedor',
            name='valor_alcada',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Limite máximo de desconto permitido ao vendedor.', max_digits=12),
        ),
    ]
